require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe QuotationLinesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # QuotationLine. As you add validations to QuotationLine, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { category: '',
      name: 'My string',
      quotation_id: 1,
      quantity: 1,
      unit_price: 9.99,
      position: 1
       }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # QuotationLinesController. Be sure to keep this updated too.
  def valid_session
    {"warden.user.user.key" => session["warden.user.user.key"]}
  end

  before do
    # user = double('user')
    # request.env['warden'].stub :authenticate! => user
    request.env['HTTP_REFERER'] = '/'
    # controller.stub :current_user => user
    # user.stub(:has_role?) do |role|
    #   if role == 'sales_quote'
    #     true
    #   end
    # end
    user = instance_double('user', :id => 1)
    allow(request.env['warden']).to receive(:authenticate!).and_return(user)
    allow(controller).to receive(:current_user).and_return(user)
    allow(user).to receive(:has_role?).and_return(true)

    @quotation = FactoryGirl.create(:quotation)   # so quotation 1 exists for valid attributes
    params = {}
    params[:quotation] = @quotation
    allow(controller).to receive(:session).and_return({return_to: quotations_path})  # for redirects to return_to path
  end

  describe "GET show" do
    it "assigns the requested quotation_line as @quotation_line" do
      quotation_line = QuotationLine.create! valid_attributes.merge(quotation_id: @quotation.id)
      get :show, {quotation_id: @quotation, quotation: @quotation.id, :id => quotation_line.to_param}, valid_session
      expect(assigns(:quotation_line)).to eq(quotation_line)
    end
  end

  describe "GET edit" do
    it "assigns the requested quotation_line as @quotation_line" do
      quotation_line = QuotationLine.create! valid_attributes.merge(quotation_id: @quotation.id)
      get :edit, {quotation_id: @quotation, :id => quotation_line.to_param}, valid_session
      expect(assigns(:quotation_line)).to eq(quotation_line)
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested quotation_line" do
        quotation_line = QuotationLine.create! valid_attributes.merge(quotation_id: @quotation.id)
        # Assuming there are no other quotation_lines in the database, this
        # specifies that the QuotationLine created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        allow_any_instance_of(QuotationLine).to receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {quotation_id: @quotation, :id => quotation_line.to_param, :quotation_line => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested quotation_line as @quotation_line" do
        quotation_line = QuotationLine.create! valid_attributes.merge(quotation_id: @quotation.id)
        put :update, {quotation_id: @quotation, :id => quotation_line.to_param, :quotation_line => valid_attributes.merge(quotation_id: @quotation.id)}, valid_session
        expect(assigns(:quotation_line)).to eq(quotation_line)
      end

      it "redirects to the quotation_line" do
        quotation_line = QuotationLine.create! valid_attributes.merge(quotation_id: @quotation.id)
        put :update, {quotation_id: @quotation, :id => quotation_line.to_param, :quotation_line => valid_attributes.merge(quotation_id: @quotation.id)}, valid_session
        expect(response).to redirect_to(quotations_path)
      end
    end

    describe "with invalid params" do
      it "assigns the quotation_line as @quotation_line" do
        quotation_line = QuotationLine.create! valid_attributes.merge(quotation_id: @quotation.id)
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(QuotationLine).to receive(:save).and_return(false)
        put :update, {quotation_id: @quotation, :id => quotation_line.to_param, :quotation_line => { "name" => "invalid value" }}, valid_session
        expect(assigns(:quotation_line)).to eq(quotation_line)
      end

      it "re-renders the 'edit' template" do
        quotation_line = QuotationLine.create! valid_attributes.merge(quotation_id: @quotation.id)
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(QuotationLine).to receive(:save).and_return(false)
        put :update, {quotation_id: @quotation,:id => quotation_line.to_param, :quotation_line => { "name" => "invalid value" }}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    # before do
    #   controller.request.stub(:referer).and_return quotation_lines_index_path
    # end
    it "destroys the requested quotation_line" do
      quotation_line = QuotationLine.create! valid_attributes.merge(quotation_id: @quotation.id)
      expect {
        delete :destroy, {quotation_id: @quotation, id: quotation_line.to_param}, valid_session
      }.to change(QuotationLine, :count).by(-1)
    end

    it "redirects to the referer" do
      quotation_line = QuotationLine.create! valid_attributes.merge(quotation_id: @quotation.id)
      delete :destroy, {quotation_id: @quotation, id: quotation_line.to_param}, valid_session
      expect(response).to redirect_to(root_path)
    end
  end

  describe "POST sort" do
    it "sorts by an array of ids" do
      @line1 = QuotationLine.create! valid_attributes.merge({position: 1, quotation_id: @quotation.id})
      @line2 = QuotationLine.create! valid_attributes.merge({position: 2, quotation_id: @quotation.id})
      @line3 = QuotationLine.create! valid_attributes.merge({position: 3, quotation_id: @quotation.id})
      @line4 = QuotationLine.create! valid_attributes.merge({position: 4, quotation_id: @quotation.id})

      # quote_lines = ["4","3","1","2"]
      quote_lines = [@line4.id,@line3.id,@line1.id,@line2.id]

      post :sort, {quotation_line: quote_lines}, valid_session
      @line1.reload
      @line2.reload
      @line3.reload
      @line4.reload
      expect(@line1.position).to eq(3)
      expect(@line2.position).to eq(4)
      expect(@line3.position).to eq(2)
      expect(@line4.position).to eq(1)
    end
  end

end
